/* =========================================================
   Generates NEEDS-INPUT.md and SHOT-LIST.md from the registries in
   src/config, then checks that the registries and the pages agree.

   The point of running this as part of `npm run build` is that neither
   document can go stale. If a gap is filled and its entry deleted, the build
   reports the pages still referencing it. If a page stops using a marker, the
   build reports the orphan. Neither is fatal — a warning is enough, because
   the state of the site during a photo shoot is legitimately in flux.

   This is an AUTHORING aid, not part of the production build, which is why
   `npm run build` does not call it — use `npm run build:docs` locally. It
   imports the registries as TypeScript directly, which relies on Node's type
   stripping (default from 22.18 / 24). Vercel picks its own Node version, and
   a deploy should never fail because a markdown file could not be regenerated.

   Run on its own with:  npm run needs-input
   ========================================================= */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'src');

/* Node 24 strips TypeScript types on import, so the registries can be read
   directly rather than duplicated or parsed by hand. */
const { gaps } = await import('../src/config/needs-input.ts');
const { shots } = await import('../src/config/shots.ts');

/* --- collect every source file -------------------------------------- */
async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (['.astro', '.ts', '.js', '.mjs'].includes(extname(entry.name))) {
      out.push(full);
    }
  }
  return out;
}

/* The serverless function is scanned too: two of the gaps are environment
   variables that only that file knows about. */
const files = [
  ...(await walk(SRC)),
  ...(await walk(join(ROOT, 'api'))),
  join(ROOT, 'astro.config.mjs'),
];
const sources = await Promise.all(
  files.map(async (f) => ({
    path: relative(ROOT, f).replace(/\\/g, '/'),
    text: await readFile(f, 'utf8'),
  }))
);

/* --- where is each key actually used? -------------------------------- */
function usedIn(key, patterns) {
  return sources
    .filter((s) => patterns.some((p) => p(key).test(s.text)))
    .map((s) => s.path);
}

const gapPatterns = [
  // <NeedsInput key="address" />
  (k) => new RegExp(`key=["']${k}["']`),
  // [needs-input: address] in a comment
  (k) => new RegExp(`needs-input:\\s*${k}\\b`),
];

const shotPatterns = [
  // <Placeholder shot="hero-build" />
  (k) => new RegExp(`shot=["']${k}["']`),
  // A shot that is needed but has no visible slot — the share card, which is
  // a meta tag rather than an element. Marked in a comment as:
  //   reserved-shot: og-share
  (k) => new RegExp(`reserved-shot:\\s*${k}\\b`),
];

const gapUsage = Object.fromEntries(
  Object.keys(gaps).map((k) => [k, usedIn(k, gapPatterns)])
);
const shotUsage = Object.fromEntries(
  Object.keys(shots).map((k) => [k, usedIn(k, shotPatterns)])
);

/* --- NEEDS-INPUT.md -------------------------------------------------- */
const bySeverity = (sev) =>
  Object.entries(gaps).filter(([, g]) => g.severity === sev);

const section = (entries) =>
  entries
    .map(([key, g]) => {
      const where = gapUsage[key];
      const shown = where.length
        ? where.map((w) => `\`${w}\``).join(', ')
        : '_not referenced anywhere — either fill it in or delete the entry_';
      return `### ${g.label}\n\n${g.why}\n\nAppears in: ${shown}\n`;
    })
    .join('\n');

const launch = bySeverity('launch');
const content = bySeverity('content');

const needsInputDoc = `# Needs input

Generated by \`npm run build\`. Do not edit by hand — edit
\`src/config/needs-input.ts\` and rebuild.

Nothing on this site was invented to fill a gap. Every item below is a fact
that was not in the brief, and every one of them renders on the page as a
visible \`[ needs input — … ]\` marker until it is answered.

**${launch.length} blocking launch · ${content.length} would improve the site**

---

## Blocking launch

${section(launch)}
---

## Would improve the site

${section(content)}
---

### How to clear one

1. Put the real value where the entry says it goes.
2. Delete its entry from \`src/config/needs-input.ts\`.
3. Run \`npm run build\`. It will name any page still referencing the marker.

_Last generated ${new Date().toISOString().slice(0, 10)}._
`;

await writeFile(join(ROOT, 'NEEDS-INPUT.md'), needsInputDoc, 'utf8');

/* --- SHOT-LIST.md ---------------------------------------------------- */
const priorityOrder = { must: 0, should: 1, nice: 2 };
const priorityLabel = {
  must: 'Must have',
  should: 'Worth having',
  nice: 'If there is time',
};

/* A shot with a file attached has been taken. It moves to the "already have
   one" list rather than staying on the brief, so the document shrinks as the
   photography lands instead of quietly going stale. */
const allShots = Object.entries(shots);
const doneShots = allShots.filter(([, s]) => s.file);
const shotEntries = allShots
  .filter(([, s]) => !s.file)
  .sort((a, b) => priorityOrder[a[1].priority] - priorityOrder[b[1].priority]);

const grouped = shotEntries.reduce((acc, [key, s]) => {
  (acc[s.priority] ||= []).push([key, s]);
  return acc;
}, {});

const shotSection = (entries) =>
  entries
    .map(([key, s]) => {
      const slots = shotUsage[key];
      const count = slots.length;
      return [
        `### ${s.label}`,
        '',
        `**Ratio:** \`${s.aspect}\`${
          s.aspect === '1 / 1'
            ? ' — square'
            : s.aspect === '4 / 5'
              ? ' — vertical'
              : ' — landscape'
        }`,
        '',
        s.direction,
        '',
        count
          ? `Used on: ${slots.map((w) => `\`${w}\``).join(', ')}`
          : '_No slot on the site uses this shot._',
        '',
      ].join('\n');
    })
    .join('\n');

const totalSlots = Object.values(shotUsage).reduce(
  (n, arr) => n + arr.length,
  0
);

const shotListDoc = `# Shot list

Generated by \`npm run build\` from the slots that actually exist in the build.
Do not edit by hand — edit \`src/config/shots.ts\`.

**${shotEntries.length} still to shoot. ${doneShots.length} already covered.**

Shoot landscape for anything marked landscape. A vertical phone frame cropped
to 16:9 loses most of the machine.

---

## Still to shoot

${shotEntries.length ? '' : '_Nothing — every slot on the site has a photograph._\n'}
${grouped.must ? `### Must have\n\n${shotSection(grouped.must)}` : ''}
${grouped.should ? `### Worth having\n\n${shotSection(grouped.should)}` : ''}
${grouped.nice ? `### If there is time\n\n${shotSection(grouped.nice)}` : ''}
---

## Already covered

These slots have a real photograph in \`src/assets/photos/\`. Replace the file
if a better frame turns up — nothing else needs to change.

${doneShots.map(([key, s]) => `- **${s.label}** — \`${s.file}\``).join('\n')}

---

_Last generated ${new Date().toISOString().slice(0, 10)}._
`;

await writeFile(join(ROOT, 'SHOT-LIST.md'), shotListDoc, 'utf8');

/* --- drift check ----------------------------------------------------- */
/* Only `launch` gaps are expected to appear on a page — NeedsInput.astro
   refuses to render anything else, so a `content` gap with no reference is the
   designed state, not drift. Warning about those four every build would teach
   everyone to ignore this output, which costs more than it catches. */
const orphanGaps = Object.entries(gapUsage).filter(
  ([key, where]) => !where.length && gaps[key].severity === 'launch'
);
const orphanShots = Object.entries(shotUsage).filter(([, w]) => !w.length);

console.log(
  `needs-input: ${launch.length} launch-blocking, ${content.length} content gaps → NEEDS-INPUT.md`
);
console.log(
  `shot-list:   ${shotEntries.length} shots across ${totalSlots} slots → SHOT-LIST.md`
);

for (const [key] of orphanGaps) {
  console.warn(
    `  warning: gap "${key}" is registered but no page references it.`
  );
}
for (const [key] of orphanShots) {
  console.warn(
    `  warning: shot "${key}" is registered but no slot uses it.`
  );
}
